services:
  backend:
    image: ghcr.io/runzhliu/welink/backend:main
    build: ./backend
    container_name: welink-backend
    ports:
      - "8080:8080"
    volumes:
      - ../wechat-decrypt/decrypted_with_wal:/app/data
      - /Users/thedawn/Library/Containers/com.tencent.xinWeChat/Data/Documents/xwechat_files/wxid_cd9h7an356ri31_7ca5/msg:/app/msg:ro
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - GIN_MODE=release
      - MSG_DIR=/app/msg

  frontend:
    image: ghcr.io/runzhliu/welink/frontend:main
    build: ./frontend
    container_name: welink-frontend
    ports:
      - "3000:80"
    volumes:
      - /Users/thedawn/Library/Containers/com.tencent.xinWeChat/Data/Documents/xwechat_files/wxid_cd9h7an356ri31_7ca5/msg:/usr/share/nginx/html/wechat-msg:ro
    depends_on:
      - backend
